appVersion: '3'
services:
  discord-bot:
    build:
      context: .
    depends_on:
      - mysql
    environment:
      - DISCORD_BOT_TOKKEN=value
      - MYSQL_URL=value

  mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"