version: '3.8'
services:
  application:
    image: choigunwoo/discord-bot:a1.0.5
    container_name: discord_bot_app
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - bot_network
#####################################################################################
  mysql:
    image: mysql:lts
    container_name: discord_bot_db
    environment:
      MYSQL_ROOT_PASSWORD: meat9563
      MYSQL_DATABASE: discord_bot
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/mysql
    networks:
      - bot_network
#####################################################################################
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "30001:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - bot_network
#####################################################################################
  # argocd:
  #   image: argoproj/argocd:v2.6.15 # Current argocd latest version is 2.6.15
  #   container_name: argocd
  #   ports:
  #     - "30002:80"
  #     - "50002:443"
  #   volumes:
  #     - argocd_apps:/apps
  #   networks:
  #     - bot_network
#####################################################################################
networks:
  bot_network:
    driver: bridge
#####################################################################################
volumes:
  mysql_data:
  jenkins_home:
  argocd_apps: