version: '3.8'
services:
  application:
    image: choigunwoo/discord-bot:a1.0.5
    container_name: discord_bot_app
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "30000:30000"
    networks:
      - discord_network
#####################################################################################
  mysql:
    image: mysql:lts
    container_name: discord_bot_db
    environment:
      MYSQL_ROOT_PASSWORD: meat9563
      MYSQL_DATABASE: discord_bot
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - discord_bot_volume:/var/mysql
    networks:
      - discord_network
#####################################################################################
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "30001:8080"
      - "50000:50000"
    volumes:
      - discord_bot_volume:/var/jenkins_home
    networks:
      - discord_network
#####################################################################################
  argocd:
    image: argoproj/argocd:v2.6.15 # Current argocd latest version is 2.6.15
    container_name: argocd
    command: ["/usr/local/bin/argocd-server", "--server", "0.0.0.0:8081"]
    ports:
      - "30002:8080"
      - "443:443"
    volumes:
      - discord_bot_volume:/apps
    networks:
      - discord_network
#####################################################################################
networks:
  discord_network:
    driver: bridge
#####################################################################################
volumes:
  discord_bot_volume: