pub fn request() -> CreateCommand {
  CreateCommand::new("aws").description("AWS service access control")
  .add_option(CreateCommandOption::new(CommandOptionType::SubCommand, "region", "Current Region"))
  .add_option(CreateCommandOption::new(CommandOptionType::SubCommandGroup, "ec2", "EC2 Instance Command")
    .add_sub_option(CreateCommandOption::new(CommandOptionType::SubCommand, "list", "Instance list")
      .add_sub_option(CreateCommandOption::new(CommandOptionType::String, "filter", "Instance scale filter")
        .add_string_choice("all", "All Instance")
        .add_string_choice("running", "Running Instance")
        .add_string_choice("stopped", "Stopped Instance")
        .add_string_choice("terminated", "Terminated Instance")
        .required(true)
      )
    )
    .add_sub_option(CreateCommandOption::new(CommandOptionType::SubCommand, "status", "Instance Status")
      .add_sub_option(CreateCommandOption::new(CommandOptionType::Number, "instance_number", "Instance Number")
        .required(true)
      )
      .add_sub_option(CreateCommandOption::new(CommandOptionType::String, "actions", "Instance Actions")
        .add_string_choice("start", "Start Instance")
        .add_string_choice("stop", "Stop Instance")
        .add_string_choice("reboot", "Reboot Instance")
        .add_string_choice("terminate", "Terminate Instance")
        .required(true)
      )
    )
  )
}