name: Docker image ci
on:
  push:
    branches: [ "main" ]
    paths-ignore: [
      "LICENSE",
      ".gitignore",
      ".dockerignore",
      "Dockerfile",
      ".env.*",
      "**/*.md",
      "**/*.png",
      "**/*.jpg",
      "**/*.svg",
      "**/**/*.yml",
      "**/**/*.yaml",
      "*.toml",
      "*.ps1",
    ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_USERTOKEN: ${{ secrets.DOCKERHUB_USERTOKEN }}

jobs:
  Image-build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ "ubuntu-latest" ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Set repository Name
        run: |
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Docker image tag
        run: |
          echo "IMAGE_TAG=a1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Docker user login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_USERTOKEN }}

      - name: Docker image build
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: false
          tags: "${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}"

  Image-Push:
    runs-on: ${{ matrix.runner }}
    needs: [ Image-build ]
    strategy:
      matrix:
        runner: [ "ubuntu-latest" ]

    steps:
      - name: Docker user login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_USERTOKEN }}

      - name: Docker image push
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          tags: "${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}"