name: Golang workflow CI

on:
  push: 
    branches: ["master"]
    paths-ignore:
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2 # Current checkout latest[4.2.2]

      - name: Set up Golang
        uses: actions/setup-go@v5.3.0 # Current setup-go latest[5.3.0]
        with:
          go-version: '1.24.0' # Current Golang latest[1.24.0] link = https://go.dev/dl/